# Generated by Django 4.0.5 on 2022-07-10 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_tag_alter_playing_options_alter_playing_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='tags',
            field=models.ManyToManyField(to='main_app.tag'),
        ),
    ]
